### ISSUE TITLE
[Vulkan]: Basic abstraction over rendering flow

### ISSUE THREAD

**Issue by zCubed3** [zCubed3/sapphire#1]
# Problem
Currently our Vulkan abstraction layer "VAL" is missing any form of abstraction for pipelines and render passes. This means creating pipelines is slow and unsafe (in regards to VAL safety)

# Tasks
- [x] Abstraction for VkPipeline
- [x] Abstraction for VkPipelineLayout
- [x] Abstraction for VkRenderPass
- [X] Abstraction for VkDescriptorSet
- [X] Abstraction for VkDescriptorSetLayout

**Comment by zCubed3** [comment]
68fad5290c1f8effd57b2228960d029008f02101: Added `ValVertexInputBuilder` to create vertex input structures in a builder style
833017bcb3db7ca957ab2cec4b0ce3038e9ab35c: WIP `ValPipelineBuilder`, simplifying most properties into booleans, flags, or enums
95fe8b762ad0e78478deeb6a8640cdd1b8222a71: Added `ValDescriptorSetBuilder` to abstract the process of creating descriptor layouts and sets

**Comment by zCubed3** [comment]
Closing and breaking into several other issues
